name: Push new docker container

on:
  workflow_run:
    workflows: ['Run Tests']
    branches: [ main ]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - run: echo '${{ github.ref }}'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo '${{ github.ref }}'
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'
    - name: Log in to the container registry
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: dockerPush
